set_operating_conditions -design_power_budget 5.0

set_property IOSTANDARD LVCMOS33 [get_ports {A[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {A[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {A[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {A[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {A[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {A[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {A[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {A[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {A[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {A[10]}]
set_property PACKAGE_PIN V17 [get_ports {A[1]}]
set_property PACKAGE_PIN V16 [get_ports {A[2]}]
set_property PACKAGE_PIN W16 [get_ports {A[3]}]
set_property PACKAGE_PIN W17 [get_ports {A[4]}]
set_property PACKAGE_PIN W15 [get_ports {A[5]}]
set_property PACKAGE_PIN V15 [get_ports {A[6]}]
set_property PACKAGE_PIN W14 [get_ports {A[7]}]
set_property PACKAGE_PIN W13 [get_ports {A[8]}]
set_property PACKAGE_PIN V2 [get_ports {A[9]}]
set_property PACKAGE_PIN T3 [get_ports {A[10]}]

set_property IOSTANDARD LVCMOS33 [get_ports {F[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {F[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {F[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {F[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {F[5]}]
set_property PACKAGE_PIN U16 [get_ports {F[5]}]
set_property PACKAGE_PIN E19 [get_ports {F[4]}]
set_property PACKAGE_PIN U19 [get_ports {F[3]}]
set_property PACKAGE_PIN V19 [get_ports {F[2]}]
set_property PACKAGE_PIN W18 [get_ports {F[1]}]
