set_property IOSTANDARD LVCMOS33 [get_ports {P[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {P[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {P[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {P[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {P[5]}]

set_property PACKAGE_PIN V17 [get_ports {P[1]}]
set_property PACKAGE_PIN V16 [get_ports {P[2]}]
set_property PACKAGE_PIN W16 [get_ports {P[3]}]
set_property PACKAGE_PIN W17 [get_ports {P[4]}]
set_property PACKAGE_PIN W15 [get_ports {P[5]}]


set_property IOSTANDARD LVCMOS33 [get_ports {S[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S[11]}]

set_property PACKAGE_PIN U16 [get_ports {S[11]}]
set_property PACKAGE_PIN E19 [get_ports {S[10]}]
set_property PACKAGE_PIN U19 [get_ports {S[9]}]
set_property PACKAGE_PIN V19 [get_ports {S[8]}]
set_property PACKAGE_PIN W18 [get_ports {S[7]}]
set_property PACKAGE_PIN U15 [get_ports {S[6]}]
set_property PACKAGE_PIN U14 [get_ports {S[5]}]
set_property PACKAGE_PIN V14 [get_ports {S[4]}]
set_property PACKAGE_PIN V13 [get_ports {S[3]}]
set_property PACKAGE_PIN V3 [get_ports {S[2]}]
set_property PACKAGE_PIN W3 [get_ports {S[1]}]

